[package]
name = "rbmath"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
log = {workspace = true}
once_cell = "1.17.1"
roxmltree = "0.18.0"
smallvec = {workspace = true}
brl = {path = "../brl"}
